### PR TITLE
Fixed build issue in tests for TypeSafeConfig Config Source and cleaned up some dead code.

### PR DESCRIPTION
**Pull request by enoren**

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Thanks !

**Comment by phillip-kruger** [comment]
Hi @enoren, seems like the build is failing for another reason. I'll look at it a bit later. Thanks !

**Comment by enoren** [comment]
@phillip-kruger The previous PR had an issue with it that caused the build to fail when merged into master so this PR is intended to fix that. It does appear that there is an issue with the Travis CI build though such that PR builds fail for an unrelated reason which is why I didn't notice the issue with the original PR failing the tests.

This PR actually needs to be merged into master and not just closed in order to fix the build break on master.

**Comment by phillip-kruger** [comment]
@enoren Ok, if I start the build manually, I get this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project configsource-typesafeconfig: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/microprofile-extensions/config-ext/configsource-typesafeconfig/src/test/java/org/microprofileext/config/source/typesafeconfig/TypeSafeConfigConfigSourceTest.java:[12,26] package org.mockito does not exist
[ERROR] /home/travis/build/microprofile-extensions/config-ext/configsource-typesafeconfig/src/test/java/org/microprofileext/config/source/typesafeconfig/TypeSafeConfigConfigSourceTest.java:[12,1] static import only from classes and interfaces

Is this something you can fix ?

**Comment by derekm** [comment]
@phillip-kruger -- That should be what this PR fixes, it brings in `mockito-core` for the `test` scope.

**Comment by phillip-kruger** [comment]
@enoren @derekm - aa, ok, I am a bit slow. merging now, and kicking of the build

**Comment by phillip-kruger** [comment]
@enoren @derekm - Build successful ! Thanks !
Should we release ? (then the artifact will be available in maven central)

**Comment by enoren** [comment]
@phillip-kruger I am good with releasing, but then I am biased. We are already using this capability in two projects here and havent run into any issues and would like to be able to consume this from here and would need a released version to do so. So you have my vote!

**Pull request merged**
