### PR TITLE
Fixes log statement

### PR DESCRIPTION
**Pull request by cmspray**
Let me know if you need any info here or anything else from me.

### CODE REVIEW

**Comment by cmspray** [comment]
I couldn't find any contribution guidelines so I'm not sure what branch you'd like me to request to merge into?

@phillip-kruger maybe you could be of some assistance here?

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Thanks @cmspray !!

**Comment by cmspray** [comment]
No problem!

@phillip-kruger any timeline for cutting a new release? I wasn't sure if this project was even still alive.

**Comment by phillip-kruger** [comment]
It's being revived :) I'll cut a release soon. What is your timeline ?

**Comment by cmspray** [comment]
No real timeline, was just curious on what the timeline here was!

Thanks again!

**Comment by phillip-kruger** [comment]
I have a few things to add , then I'll cut a release. Let aim for early next week ?

**Comment by cmspray** [comment]
Sounds good, thanks @phillip-kruger!

**Comment by cmspray** [comment]
Hate to nag, but are there any updates on this?

**Comment by phillip-kruger** [comment]
Let me do a patch release for this, as my upcoming changes is big.

**Comment by cmspray** [comment]
Thank you so much, I appreciate it!

**Comment by phillip-kruger** [comment]
I am strugling with sonatype, seems my key expired. So it might take a bit longer. I'll spend some time over the weekend to sort out my key. I can not remember how / what to do so need to Google a bit :)

**Comment by phillip-kruger** [comment]
@cmspray -  Ok, I sorted out my keys and did a release eventually ! Version 1.0.10 is out ! It might take a few hours before it reflect in Maven Central.

**Comment by cmspray** [comment]
👍 Thanks again!

**Pull request merged**
